# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23297b57a7a00689a2124519ca1c99eac72314d55af3c15ddd01f5f76112f6ff8b6666bb379437d92887193a4a87125f6d802c537423269750901a1792914a56

test:
  secret_key_base: bd7f3e276c9434cbe84d7e43cd1bde179e0c6fc9abc4cafaa153f7e7e44f431a08fa12e84415d3255fd5bea790e1a45a18dcbb08ad4adc90e899a0bf658c34d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
